// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAiheW65P32oD6y1VAbAA-VWUT18Nztik',
    appId: '1:665891302896:web:3fca264a646cacfce60135',
    messagingSenderId: '665891302896',
    projectId: 'online-classroom-3085e',
    authDomain: 'online-classroom-3085e.firebaseapp.com',
    databaseURL: 'https://online-classroom-3085e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'online-classroom-3085e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJy4RNgamWcJkNYzfJB9rwjQDREaME_hY',
    appId: '1:665891302896:android:c497b06d888a6221e60135',
    messagingSenderId: '665891302896',
    projectId: 'online-classroom-3085e',
    databaseURL: 'https://online-classroom-3085e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'online-classroom-3085e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbAS_kypsmzgQoJDApzrDzTzk_wFCQ2cw',
    appId: '1:665891302896:ios:0c95617d148d9f2ce60135',
    messagingSenderId: '665891302896',
    projectId: 'online-classroom-3085e',
    databaseURL: 'https://online-classroom-3085e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'online-classroom-3085e.appspot.com',
    iosClientId: '665891302896-nbuufs4a07ab9kfl0h000ffr97nqniro.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineClassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbAS_kypsmzgQoJDApzrDzTzk_wFCQ2cw',
    appId: '1:665891302896:ios:bc3baad5ec7368f1e60135',
    messagingSenderId: '665891302896',
    projectId: 'online-classroom-3085e',
    databaseURL: 'https://online-classroom-3085e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'online-classroom-3085e.appspot.com',
    iosClientId: '665891302896-siic0oof1jhogjncdahmnmf41p8pcr32.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineClassroom.RunnerTests',
  );
}
